### ISSUE TITLE
shasum mismatch

### ISSUE THREAD

**Issue by tdjsnelling** [isaacs/nave#100]
I am getting a `shasum mismatch` error whenever I try and use a different version of node, even though the hashes printed are identical. It doesn't matter which version I try to install. E.g.

```
$ nave use 11.4.0
######################################################################## 100.0%
shasum mismatch, expect 05a515146d5bc397625f442a6ecbbc7f0d071a2a7efbf1e2b2ed46d728bc7b30, got 05a515146d5bc397625f442a6ecbbc7f0d071a2a7efbf1e2b2ed46d728bc7b30
```

OS: macOS Mojave 10.14.5
Nave installed with `npm i nave -g`

**Comment by bertjwregeer** [comment]
I would recommend trying to blow away your cache:

```
rm -rf ~/.nave/cache/
```

and trying again.

**Comment by isaacs** [comment]
The shasums being printed being identical is a dumb typo.  (It was printing `$shasum` for both, instead of `$actualshasum`.)

If you upgrade to the latest release, it'll either fix the problem, or fail in a new way which provides more information.
