### ISSUE TITLE
How to delete a named environment

### ISSUE THREAD

**Issue by lebolo** [isaacs/nave#103]
To delete a named environment, do I `rm -rf ~/.nave/installed/<named_env>`?

**Comment by lebolo** [comment]
Ack sorry, didn't think you could `nave uninstall <named_env>`, thought it was just used for installed versions of node 🙄Feeling dumb!

**Comment by isaacs** [comment]
Huh, that'd maybe be worth mentioning in the docs.  I can see how you'd make that assumption.

The `rm -rf` option also works just fine :)
