### ISSUE TITLE
Auto fails using fish as nave_run executed with exec

### ISSUE THREAD

**Issue by Asheboy** [isaacs/nave#107]
When running `nave auto` under fish shell I get the following:

```
~/.nave/.zshenv (line 2): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
[ "$NAVE_DEBUG" != "" ] && set -x || true
                         ^
from sourcing file ~/.nave/.zshenv
        called on line 230 of file /usr/share/fish/config.fish

in function “.”
        called on standard input
```

This is because `nave_run` is executed with `exec` and therefore hits this block https://github.com/isaacs/nave/blob/master/nave.sh#L796, when it needs to reach https://github.com/isaacs/nave/blob/master/nave.sh#L816 to execute the `.zshenv` via bash.

**Comment by isaacs** [comment]
Correct.  The `nave auto` magic only works in bash, because nave is a bash program.
