### ISSUE TITLE
Unable to install any node with nave on Windows 10.

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [isaacs/nave#110]
/c/Users/rg735009/AppData/Roaming/npm/node_modules/nave/nave.sh: line 384: make: command not found
Failed to make 7.10.1
failed to install 7.10.1

I have WIndows 10 + git bash + WSL installed

**Comment by isaacs** [comment]
You have to have `make` installed if you are trying to get a version that doesn't have a precompiled binary for WSL.  (AFAIK, there are no precompiled node binaries for WSL.)
