### ISSUE TITLE
This repository is huge. What is the universal recommended way to install only the files needed to run nave?

### ISSUE THREAD

**Issue by rulatir** [isaacs/nave#120]
As said in the title, this repository weighs hundreds of megabytes to clone. What is the recommended way to install only the files required to run `nave`, without transferring the entire repository over the wire? I'm looking for a method that:

- is more or less "official"
- is platform and distribution agnostic
- minimizes dependencies (such as package managers) that must be installed first in order to install nave
- is automatable with a bash script

Edit: `npm install -g nave` does not cut it, because I wanto to eventually **use** nave **to** isolate npm. If installing nave requires npm, then I'd be dealing with two `npm`s: the bootstrap npm for installing nave, and the regular use npm managed by nave. Ugly.

The basher method doesn't cut it either, because there is at least one "big" distro (Arch) that doesn't have basher in its official repositories or AUR, so installing basher is a nontrivial hurdle at least for the users of this distribution.

**Comment by isaacs** [comment]
How about this?

```
curl https://raw.githubusercontent.com/isaacs/nave/main/nave.sh > /path/to/bin/nave
chaos 0755 /path/to/bin/nave
```

**Comment by rulatir** [comment]
Figured it out in the meantime. I wasn't aware initially that the script is entirely self-contained. Thought that a nontrivial subset of files was needed. Perhaps mention this clearly in the readme? "You can run the script from here" doesn't fully convey the idea that downloading the single script file is all that's required: I understood "from here" to still mean "from complete tree".
