### ISSUE TITLE
Is it possible to define environment variables, or specify a shell script to be sourced, per environment?

### ISSUE THREAD

**Issue by rulatir** [isaacs/nave#121]
It looks like `pnpm` recently (or not) began insisting on `$PNPM_HOME` being set and added to $PATH, and I absolutely MUST keep those separate for different node environments in which I will be running `pnpm`.

Can this be done with nave?

**Comment by isaacs** [comment]
Wouldn't be hard to add.  What is it typically set to?  What goes in that path?

**Comment by isaacs** [comment]
But yes, you can run something in every nave env you enter by dropping a file at `~/.config/.naverc` if `~/.config` exists and `~/.nave` does not exist, or `~/.naverc` otherwise.  That script will have all the various `NAVE*` environment variables set, and it's sourced in the shell, so you can `export` whatever you need to.

Lmk what you land on, and maybe we can just make `$PNPM_HOME` part of the default set.

**Comment by rulatir** [comment]
I only gave `$PNPM_HOME` as an example.

I am aware of `.naverc`, but this one is always sourced by nave, while I want a file that would be sourced specifically when entering the subshell for a particular node environment and not others. My project uses two different node versions via nave, and I want to be able to set separate `$PNPM_HOME`s for each of those (for now I downgraded to pnpm v6 to avoid the problem).

I understand that code in `.naverc` knows (via environment) which particular node environment it is being sourced for, so it is probably possible to _code_ this feature in `.naverc`, but I'm not a fan of coding anything in bash that isn't a straight sequence of commands ;)

**Comment by rulatir** [comment]
Revisiting this.

I cannot use any solution that relies on non-sandboxed paths like ~/.config/.naverc. The solution **must not** require the user to modify their user-global config files in locations like ~/.config. I am not allowed to even require the user to add a _single line_ to a global config to bootstrap the solution.

This is because we strive to completely automate the install script that sets up the working environment for each new project on each workstation, and it is hard and unreliable to try to automate logic like "identify and parse user's global nave configuration script and add a line that sources a per - `$NAVE` .env file, but only if that line hasn't already been added". The whole goal is to _eliminate_ manual steps that require writing instructions for users, like "figure out what your nave config file is and add a line there that sources `~/.environments/nave/$NAVE/.env`". I can do this manual step once in my environment, but this is about a solution that will be installed repeatedly on multiple machines in multiple locations.

We really do need to be able to store all configuration pertaining to a particular node version _inside_ that version, for some sensible definition of _inside_.

**Comment by isaacs** [comment]
Weird, I just got the email about your June 5 message and most recent one at the same time, and now I don't see your most recent message here.  Maybe you deleted it?  Or GitHub or gmail got hungry?  Anyway, sorry for the slow turnaround.

> I'm not a fan of coding anything in bash that isn't a straight sequence of commands ;)

Hahah, we're fans of different things ;)

So yes, if you want a way to source some bash file that's included in a given project, that'd probably work, but the real blocker here is that you don't want to have it sourced for all projects, _or_ require that the user put anything in their home directory.  That makes sense.

Bonus points if the _filename_ had to match the nave env somehow, so if you did `nave use blah 16`, it'd look for:

* `.naverc_foo`
* `.naverc_16`
* `.naverc_16.19`
* `.naverc_16.19.0`
* `.naverc_foo-16`
* `.naverc_foo-16.19`
* `.naverc_foo-16.19.0`

Then you could set a config for any of "this named env", "any env of a version v16, v16.19, v16.19.0", or "this named env at this version".

Right now, the local `.naverc` mimics the behavior of `.nvmrc`, in that it's just arguments to `nave use` (for use with `nave auto`).  So the only weird part of this is that it would look related.  Maybe call it `.nave_profile{_...}` to avoid that confusion?  Plus, then `.nave_profile` in the local dir could just be the "run for any nave shell" variant.

**Comment by isaacs** [comment]
Won't be too hard to do, actually, just needs to be done in the shell env file that nave writes out. Then you can put whatever in whichever local config file makes sense for your project. I'll have something put together soon.

**Comment by rulatir** [comment]
I deleted my most recent comment. I took a different approach with my current problem, but I'm still using nave, and I still believe that the feature might come in handy.

I realized that since I already isolate nave itself _into_ a (gitignored) subdirectory of the project root by setting `$NAVE_DIR`, I can just create `$NAVE_DIR/.naverc` and it gets sourced just fine, and in there I can source or define whatever I want, using `$NAVE_DIR` and `$NAVE` to construct the path.

**Comment by isaacs** [comment]
Ah, perfect. I'll leave this open though, I also think it'd be handy.

**Comment by isaacs** [comment]
Landed on v3.4.0

**Comment by rulatir** [comment]
Thank you!

I just checked this new feature, and unfortunately the current semantics is insufficient for my use case. The profiles are only find-upped from $PWD, but not looked for in any location that depends **only** on $NAVE_DIR and the which-environment information - and _that_ is what I need. In my specific use case, those per-environment profiles are not supposed to be managed, or even known about, by users; they are "system".

**Comment by rulatir** [comment]
Hmm, actually the generated `.zshenv` includes `.naverc` from one level above `$NAVE_DIR`, but I can work with that.

**Comment by rulatir** [comment]
Just FYI, there's a sad plot twist: the original motivating case of pnpm turned out to be a dud anyway. In pnpm v7 they removed all possibilities of overriding the default configuration search paths. This whole issue was about making it possible to pass different envs to pnpm from different node environments, but pnpm just ignores the one crucial variable that would make the desired separation possible: `NPM_CONFIG_USERCONFIG`.

**Comment by isaacs** [comment]
What a bummer. Well, it motivated some good ideas in this tool, that's cool anyway 😅
