### ISSUE TITLE
Nave caches 500s on index fetch

### ISSUE THREAD

**Issue by andyg0808** [isaacs/nave#124]
If https://nodejs.org/dist/ 500s at the moment Nave tries to fetch it, the error page is cached, breaking all future Nave installations until the erroneous cache entry is removed.

The symptoms we saw were very similar to https://github.com/isaacs/nave/issues/99; I'm wondering if something like this happened there.

**Comment by mariusGundersen** [comment]
how do you clear the cache?

**Comment by isaacs** [comment]
You can clear the cache with `nave cache clear`.  But yes, this is an oversight, it should be passing `-f` to curl to fail on any status >= 400
