### ISSUE TITLE
humble suggestion: per project .naverc

### ISSUE THREAD

**Issue by airtonix** [isaacs/nave#57]
Just like nvm allows, when you `cd` into directory that contains an `.nvmrc` file it asks if it should run that file.

**Comment by isaacs** [comment]
Can you describe the behavior a bit more?  What would this file contain?

**Comment by ljharb** [comment]
For comparison, `.nvmrc` can contain any "versionish" - ie, anything that you could pass to `nvm use`. This includes full and partial version numbers with or without the leading `v`, local/user custom aliases, default aliases (`node`, the legacy `stable`, `iojs`, `system`), and default LTS aliases (`lts/*`, `lts/argon`, etc).

**Comment by isaacs** [comment]
What command would you run to make it actually enter that shell, though?

It sounds like you want something that will automatically run `exec nave use $(cat .naverc)` whenever you enter a directory, but this program doesn't have any hooks to run that.

**Comment by GavinDmello** [comment]
Would this require overriding the `built-in cd` and checking the pwd for a .naverc ?
Just thinking out loud.

**Comment by airtonix** [comment]
I think all it has to support is that `nave use` should attempt to find
something versionish in a .naverc file.

**Comment by isaacs** [comment]
Instructions: https://github.com/isaacs/nave#automagical

Requires a bit of `exec` magic, but it should work just fine.
