### ISSUE TITLE
Wrong symbolic link with nave use <name> <ver>

### ISSUE THREAD

**Issue by morettoni** [isaacs/nave#59]
When you create a named env with:

```
nave use <name> <ver>
```

some links inside `~/.nave/installed/dev/bin` are wrong, the **node-waf** and **npm** links to the wrong places:

```
node-waf -> ~/.nave/installed/<ver>/bin/node-waf
npm      -> ~/.nave/installed/<ver>/lib/node_modules/npm/bin/npm-cli.js
```

but the correct link for npm is:

```
npm -> ~/.nave/installed/<ver>/lib/node_modules/npm/bin/npm-cli.js
```

or directly to the npm link to `~/.nave/installed/<ver>/bin/npm`

Not sure if **node-waf** is used in recent **node.js** version (I can't see any binary with that name).

**Comment by knownasilya** [comment]
I get the following when using `nave use my-env 1.7.1`

```no-highlight
/Users/iradchenko/.nave/installed/my-env/bin/npm: line 2: /Users/iradchenko/.nave/installed/my-env/bin/iojs: No such file or directory
/Users/iradchenko/.nave/installed/my-env/bin/npm: line 2: exec: /Users/iradchenko/.nave/installed/my-env/bin/iojs: cannot execute: No such file or directory
```

**Comment by knownasilya** [comment]
Ping @isaacs

**Comment by knownasilya** [comment]
Ping @isaacs

**Comment by isaacs** [comment]
This was only a problem with some early versions of io.js as far as I can tell.  Works as designed for all versions of node currently supported.
