### ISSUE TITLE
presence of -rc1 in versions breaks things

### ISSUE THREAD

**Issue by malecki** [isaacs/nave#71]
Node have just released http://nodejs.org/dist/v0.12.3-rc1/ , which shows up in the remote nave ls, but `nave use stable …` tries to use it and 404s because it has stripped the -rc1 part.

**Comment by ljharb** [comment]
This has also broken `nvm`: https://github.com/creationix/nvm/issues/711

**Comment by ljharb** [comment]
Should be fixed now https://twitter.com/misterdjules/status/583788249820205059

**Comment by malecki** [comment]
See https://github.com/creationix/nvm/pull/712 if they do change things. Closing for now.
