### ISSUE TITLE
double `exec nave use ...` quits shell

### ISSUE THREAD

**Issue by webthusiast** [isaacs/nave#75]
I prefer replacing the shell with the 'naved' shell through `exec` over creating a subshell. But when I do that inside an already 'naved' shell, it exits.

**Comment by isaacs** [comment]
Fixed on v2.

This is a breaking change because it means that calling `nave use $version` will _always_ create a subshell (but only 1 sub-shell rather than 2 (the first for `nave.sh` and the second for `login`, like the double-parenthesized aside in this sentence)).
