### ISSUE TITLE
Is repo still maintained?

### ISSUE THREAD

**Issue by SirAnthony** [isaacs/nave#78]
Hello, I have lot of patches (and even more in future) for cygwin support & general improvements, like removing global installation, installing modules from list (to make deploy process simpler, I guess, it is not what you personally needed from nave). Is it better to fork to separate project, or will you sort out patches?

**Comment by doug-wade** [comment]
There have been 12 commits since you filed this issue on master; despite not being a maintainer, I feel comfortable saying "yes, it is."

**Comment by isaacs** [comment]
Yes.  It mostly works, and there's not a ton of activity, but I use nave very regularly, and fix bugs with it from time to time.
