### ISSUE TITLE
nave use sets NODE_PATH to wrong directory

### ISSUE THREAD

**Issue by feldgendler** [isaacs/nave#94]
In a `node use` shell, I expect `NODE_PATH` to point to the location where `npm install -g` puts modules.

In reality, I see `nave use` set `NODE_PATH` to `~/.nave/installed/10.11.0/lib/node`, while `npm install -g` installs modules in `~/.nave/installed/10.11.0/lib/node_modules`.

**Comment by ljharb** [comment]
It shouldn’t by default, because that would make global modules requireable - global modules, by default, and only for the command line, and requireable things by default are your dependencies - ie, locally installed things.
