### ISSUE TITLE
nave ls-remote returns empty, nave install node fails

### ISSUE THREAD

**Issue by rafinskipg** [isaacs/nave#99]
Hello

I don't know how is this issue reproducible but this is what happened to me:

I have been using nave for many time already, no problems, love it. But after upgrading to ubuntu 18, something is wrong. I had purged nodejs, and nave and install everything again but something is wrong and not working. 

When i don `nave usemain latest` i get this error

```
➜  ~ sudo nave usemain latest
#=#=- #                                                                                             
curl: (22) The requested URL returned error: 404 
shasum mismatch, expect , got 

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Binary install failed, trying source.
```

And when i do `nave ls-remote` it returns emtpy. 

Do you have any clue what might be the problem? Something with curl? (I read something like that in a nvm issue in stackoverflow). 
I just don't want to switch to another node versioning tool, i like nvm, but i am a bit stopped with this situation. I understand it might have nothing to do with nave itself, but with the upgrade of ubuntu. But anyway, you might have a clue about what could be the source of the problem, so i can fix it.
Thanks! <3

**Comment by isaacs** [comment]
It looks like curl is getting a 404 from the tar download.  Can you try running this? `NAVE_DEBUG=1 sudo nave usemain latest` and share the output?

**Comment by rafinskipg** [comment]
Sorry @isaacs whatever was the problem has disappeared, the command you told me to run made it correctly and installed the right version. 

The other day i installed NVM and maybe when installing it something was fixed on my laptop, or maybe the computer just needed to sleep. That is how science works. Thanks for your time and sorry for bothering
